- hosts: test
  remote_user: timstallmann

  connection: smart
  vars:
    mysql_packages:
        - mariadb-client
        - mariadb-server
        - python-mysqldb

  vars_files:
    - provision-server.vars.yml

  become: true
  become_method: sudo
  gather_facts: no

  pre_tasks:
    - name: Install python
      raw: apt-get install python-minimal python-pip python-mysqldb -y
      remote_user: root
    - name: Gathering facts
      remote_user: root
      setup:

  roles:
    - { role: geerlingguy.mysql }

  tasks:
    - include: subtasks/set-up-users.yml remote_user=root
    - include: subtasks/install-base-packages.yml remote_user=root
    - include: subtasks/install-php-nginx.yml remote_user=root
    - include: subtasks/install-composer.yml remote_user={{ remote_deploy_username }}
    - include: subtasks/install-drupal-console.yml remote_user={{ remote_deploy_username }}
    - include: subtasks/checkout-code-and-configure-drupal.yml remote_user={{ remote_deploy_username }}
    - include: subtasks/normalize-permissions.yml remote_user=root
    - include: subtasks/install-awscli.yml remote_user={{ remote_deploy_username }}
    - include: subtasks/import-database.yml remote_user={{ remote_deploy_username }}
    - include: subtasks/copy-files.yml remote_user={{ remote_deploy_username }}
    - include: subtasks/install-memcached.yml

# TODO: install/configure varnish


  handlers:
    - name: restart php-fpm
      service: name=php5.6-fpm state=restarted
      remote_user: root
    - name: restart nginx
      service: name=nginx state=restarted
      remote_user: root
    - name: restart mailhog
      service: name=mailhog state=restarted
      remote_user: root
    - name: restart ssh
      service: name=ssh state=restarted